apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: hola-mundo-deployment
  labels:
    app: hola-mundo-deployment
spec:
  selector:
    matchLabels:
      app: hola-mundo-deployment
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: hola-mundo-deployment
    spec:
      containers:
        - name: hola-mundo-deployment
          image: alefiengo/hola-mundo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-service
  labels:
    app: hola-mundo-service
spec:
  selector:
    app: hola-mundo-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
